apiVersion: v1
kind: Secret
metadata:
  name: rag-api-secrets
  namespace: aiplayground
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres.example.svc.cluster.local:5432/ragtest1
  SPRING_DATASOURCE_USERNAME: change-me
  SPRING_DATASOURCE_PASSWORD: change-me
  BERGET_API_KEY: change-me
