apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: europe-north1-docker.pkg.dev/myforesttracker/myforesttracker/rag-api
    newTag: "000e141"
patches:
  - path: route-patch.yaml
    target:
      kind: HTTPRoute
      name: aiplayground-route
  - path: gateway-https-patch.yaml
    target:
      kind: Gateway
      name: aiplayground-gw
